#ifndef __OAUTH_CONSTANTS__H_
#define __OAUTH_CONSTANTS__H_

// token encryption/decryption buffer size
#define OAUTH_CRYPTO_BUFSIZE				1024
#define OAUTH_BASE64_BUFSIZE				2048

// delimiters and wildcard
#define OAUTH_TOKEN_DELIM      			":"
#define OAUTH_TOKEN_WILDCARD			"*"

// versions
#define OAUTH_AUTHORIZED_CODE_VERSION1 	"V1"
#define OAUTH_ACCESS_TOKEN_VERSION1   	"V1"
#define OAUTH_REFRESH_TOKEN_VERSION1   	"V1"
#define OAUTH_USER_TOKEN_VERSION1   	"V1"
#define OAUTH_PAGE_TOKEN_VERSION1   	"V1"

// response types
#define OAUTH_TYPE_UNKNOWN					0
#define OAUTH_TYPE_AUTHORIZE_CODE			1
#define OAUTH_TYPE_ACCESS_TOKEN				2
#define OAUTH_TYPE_AUTHENTICATE_CODE		3
#define OAUTH_TYPE_ID_TOKEN					4
#define OAUTH_TYPE_CODE_AND_ID_TOKEN		5

// subject types
#define OAUTH_SUBJECT_TYPE_UNKNOWN			0
#define OAUTH_SUBJECT_TYPE_UUID				1
#define OAUTH_SUBJECT_TYPE_APP				2

// response types
#define OAUTH_GRANT_TYPE_UNKNOWN				0
#define OAUTH_GRANT_TYPE_AUTHORIZE_CODE			1
#define OAUTH_GRANT_TYPE_PASSWORD				2
#define OAUTH_GRANT_TYPE_JWT					3
#define OAUTH_GRANT_TYPE_REFRESH_TOKEN			4
#define OAUTH_GRANT_TYPE_CLIENT_CREDENTIALS		5
#define OAUTH_GRANT_TYPE_PWD_WITH_CLIENT_CREDENTIALS		6
#define OAUTH_GRANT_TYPE_UUID_WITH_CLIENT_CREDENTIALS		7

// versions
#define OAUTH_TCS_RESPONSE_SUCCESS			 	0
#define OAUTH_TCS_RESPONSE_FAILURE   			1

#define OAUTH_LIS_RESPONSE_SUCCESS			 	0
#define OAUTH_LIS_RESPONSE_FAILURE   			1
#define OAUTH_LIS_RESPONSE_UNAVILABLE   		2

#define OAUTH_AUTHID_SUCCESS					0
#define OAUTH_AUTHID_FAILURE   					1

// scopes
#define 	OAUTH_SCOPE_UNKNOWN  	 			0x00000
#define 	OAUTH_SCOPE_FNAME   				0x00001
#define 	OAUTH_SCOPE_LNAME   				0x00002
#define 	OAUTH_SCOPE_EMAIL  	 				0x00004
#define 	OAUTH_SCOPE_ROLES   				0x00008
#define 	OAUTH_SCOPE_TRACKID  				0x00010
#define 	OAUTH_SCOPE_REFRESH_TOKEN   		0x00020
#define 	OAUTH_SCOPE_PAGES   					0x00040
#define 	OAUTH_SCOPE_UUID   					0x00080
#define 	OAUTH_SCOPE_AUTOLOGIN   		0x00100
#define 	OAUTH_SCOPE_VALIDATE   				0x00200
#define 	OAUTH_SCOPE_RESERVED3   	0x00400
#define 	OAUTH_SCOPE_OPENID					0x00800
#define 	OAUTH_SCOPE_RESERVED4   			0x01000
#define 	OAUTH_SCOPE_RESERVED5   			0x02000
#define 	OAUTH_SCOPE_RESERVED6   			0x04000
#define 	OAUTH_SCOPE_RESERVED7   			0x08000
#define 	OAUTH_SCOPE_PROFILE   				(OAUTH_SCOPE_FNAME|OAUTH_SCOPE_LNAME)

//request/response headers
#define OAUTH2_CLIENT_ID_HEADER					"X-OAUTH2-CLIENT_ID"
#define OAUTH2_TRANSACTION_ID_HEADER			"X-OAUTH2-TID"
#define OAUTH2_STATUS_DESC_HEADER				"X-OAUTH-STATUS-DESCRIPTION"
#define OAUTH2_STATUS_ID_HEADER					"X-OAUTH-STATUS-ID"

// OIDC headers
#define OIDC_STATUS_HEADER				"X-OIDC-VALIDATE-STATUS"
#define OIDC_DESC_HEADER				"X-OIDC-VALIDATE-DESCRIPTION"
#define OIDC_ISSUER_HEADER				"X-OIDC-ISSUER"
#define OIDC_AUDIENCE_HEADER			"X-OIDC-AUDIENCE"
#define OIDC_SUBJECT_HEADER			"X-OIDC-SUBJECT"
#define OIDC_ROLES_HEADER				"X-OIDC-ROLES"

#define OAUTH_CONNECTION_LOCAL					0
#define OAUTH_CONNECTION_SAML   				1
#define OAUTH_CONNECTION_OAUTH2   				2

#endif // #if __OAUTH_CONSTANTS__H_
